{% set name = "co1_fish" %}
{% set version = "0.0.1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}
source:
  url: https://github.com/BioWilko/co1_fish/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed .
  entry_points:
    - co1_fish=co1_fish.co1_fish_cli:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - mappy
    - pysam
    - click
    - numpy
    - minimap2

test:
  commands:
    - co1_fish --help

about:
    home: https://github.com/artic-network/align_trim/
    license: MIT
    license_file: LICENSE
    summary: 
